### ISSUE TITLE
Are there any ways which could help me locate issues of dependency?

### ISSUE THREAD

**Issue by youjenli** [jlouns/gulp-requirejs-optimize#10]
Hi  
I am new to gulp and requirejs optimizer.  
As the screenshot shown below, this plugin output little information about the path-related issue of my amd module.  It feels troublesome to find out which file was not placed at the desired path in my source folder.

![gulp-requirejs-optimize-error](https://cloud.githubusercontent.com/assets/1283378/12262645/129b4b8e-b964-11e5-8057-6fb16b9631a5.png)

 I wonder if there is a good practice which could help me locate those issues exists in my source folder?

**Comment by jlouns** [comment]
It's telling you that it can't find `D:\git\experiment\Html5Application\src\js\delivery.js`

**Comment by youjenli** [comment]
Yeah, I know.  Problem is, how to find out the root cause of this error?  
I was optimizing a few amd modules with configuration object loaded from a json file located at the root folder of my project. The code block below is my configuration.  

```
{
    "baseUrl":"src/js",
    "paths":{
        "jquery":"libs/jquery/jquery",
        "jquery.mobile":"libs/jquery-mobile-for-synnex/jquery.mobile",
        "jquery.i18next":"libs/jquery-i18next-plugin-for-synnex/i18next.amd.withJQuery-1.8.0",
        "underscore":"libs/underscore/underscore",
        "backbone":"libs/backbone/backbone"
    },
    "shim":{
        "underscore":{
            "exports":"_"
        }
    },
    "optimize":"uglify2"
}
```

The optimization failed at the time it was going to process the module `src/js/module/dev/delivery.js`  specified in the `gulp.src([...modules...])`. 
Since there aren't any amd module depends on this source file, I wonder what was going wrong in the optimization process?

**Comment by jlouns** [comment]
Hey... I'm sorry I haven't responded to this in so long. Have you been able to track down your issue? One thing I can tell you is that since you are specifying a `baseUrl` of `src/js`, it's going to process everything relative to that directory, so if the relative path of the file you're passing in is `delivery.js` then it's going to look for `src/js/delivery.js`. You can make sure the right relative path is getting supplied by setting the `base` parameter on `gulp.src` like this:

``` js
gulp.src([...modules...], { base: 'src/js' })
```

**Comment by jlouns** [comment]
Closing this for now. Please reopen if you still have the issue.
