### ISSUE TITLE
Passing illegal module identifiers to requirejs.optimize on Windows

### ISSUE THREAD

**Issue by Kontinuation** [jlouns/gulp-requirejs-optimize#14]
Here is the context of this problem https://github.com/requirejs/r.js/pull/907 

> I submitted a test project [here](https://github.com/Kontinuation/Vint/tree/master/reqjs) to reproduce this problem.
> 
> Directly launching `node r.js ...` works fine, the windows path issue reproduces when running gulp build. `gulp-requirejs-optimize` invokes r.js using 
> 
> ```
> requirejs.optimize(optimizeOptions, null, function(err) {
>     error = err;
>     cb();
> });
> ```
> 
> where `optimizeOptions` were specified as the following object when processing `xmod.js`
> 
> ```
> { mainConfigFile: 'config.js',
>   logLevel: 2,
>   baseUrl: 'c:\\Users\\Kontinuation\\Documents\\GitHub\\Vint\\reqjs\\app\\scripts\\',
>   out: [Function],
>   generateSourceMaps: false,
>   include: 'libs\\xmod.js' }
> ```
> 
> The `include` property contains backslashes, which caused the problem, and the problem went away if I preprocess include property as unix path `libs/xmod.js` before calling optimize().

`file.relative` gives blackslash-separated paths, feeding such paths directly as module identifiers might cause unexpected problem. We might need to convert such windows-styled paths to module identifiers before calling into requirejs.

**Comment by jlouns** [comment]
Yep, that's a bug. Thanks. I'm working a fix.

**Comment by jlouns** [comment]
This should be fixed in v1.0.0.
