### ISSUE TITLE
Extra sourceMappingURL

### ISSUE THREAD

**Issue by cubitus81** [jlouns/gulp-requirejs-optimize#17]
Hi,

I tried using gulp-requirejs-optimize with sourcemaps and find that the optimized file contains two lines of sourceMappingURL

//# sourceMappingURL=main.js.build.js.map
//# sourceMappingURL=main-optimized.min.js.map

The first line should not be in the optimized file. Is there a setting that I should use to remove the first line?

Here is the code that I have.

```
var $ = require('gulp-load-plugins')();
gulp.task('optimize', function () {
        gulp.src('app/scripts/main.js')
            .pipe($.sourcemaps.init())
            .pipe($.requirejsOptimize({
                mainConfigFile: 'app/scripts/main.js',
                out: 'main-optimized.min.js',

            }))
             .pipe($.sourcemaps.write('/'))
            .pipe(gulp.dest('dist/scripts'));

});
```

Thank you.

**Comment by jlouns** [comment]
I'm not able to reproduce this with my project. Are you able to create a minimal example that contains the issue?

**Comment by cubitus81** [comment]
Hi Jonathan, 

Please find my example. If it matters, I am still using npm 2. 
[UI.zip](https://github.com/jlouns/gulp-requirejs-optimize/files/337865/UI.zip)

Thank you for your help.

**Comment by jlouns** [comment]
This is definitely a bug. uglify adds its own sourceMappingURL comment during minification which gets duplicated by gulp-sourcemaps. I'm working on a fix now.
