### ISSUE TITLE
Is it possible to do incremental builds?

### ISSUE THREAD

**Issue by mukeshsoni** [jlouns/gulp-requirejs-optimize#2]
Currently, if i hook this up with a watcher (say gulp.watch), the whole build process repeats for all the files. Is it possible to cache the read files and not process the files which are not changed.

Something similar to what is suggested here - https://github.com/gulpjs/gulp/blob/master/docs/recipes/incremental-builds-with-concatenate.md

**Comment by jlouns** [comment]
Could you share the relevant code (gulp tasks)? It may be possible depending on your use case.

**Comment by mukeshsoni** [comment]
The gulp task is similar to that shown in the example - 

```
gulp.task('scripts', function () {
    return gulp.src('src/main.js')
        .pipe(requirejsOptimize())
        .pipe(gulp.dest('dist'));
});

gulp.task('watch', function() {
  gulp.watch('src/**/*.js', ['scripts']);
});
```

Not let's say main.js has 10 dependencies each of which in turn have 10 dependencies. That will now lead to traversing 100's of files when a single file among any one of them is changed. I am also using transforms (babel) for each file which further increases the processing time for each file.

**Comment by jlouns** [comment]
Unfortunately I don't know of a way to cache the source tree for a single module. The plugin is just piping your `src/main.js` to r.js, and then r.js itself is searching for dependencies and doing the optimization/build.

Is there a reason that you need the optimization to run every time you edit a file? Normally the r.js build is only for production, and in development you would just reference `src/main.js` directly and requirejs would load all of your dependencies asynchronously.

**Comment by mukeshsoni** [comment]
we are doing the optimization step for dev too since there are 100's of js modules to be loaded per page. So a page refresh causes 100's of network requests, which becomes slow even in dev. 

Thanks for taking the time to answer the queries!

**Comment by jlouns** [comment]
Gotcha, sorry I couldn't help!
