### ISSUE TITLE
StringMap expected string key

### ISSUE THREAD

**Issue by thany** [jlouns/gulp-requirejs-optimize#23]
Somewhere in the process of this plugin, it's spewing out this error:

```
Error: StringMap expected string key
```

There are no errors in my javascript, and everything works absolutely fine. So I'm not sure what this error is on about. Furthermore, it also doesn't tell me where this error occurs, making it exceedingly hard to track down what's causing it - at least for me it is.

Is it possible to fix this? And in the mean time, work around it?

Let's have some version information as well, just in case it helps:
gulp-requirejs-optimize 1.2.0
npm 3.10.3
Gulp 3.9.1
Node 6.3.1
Windows 10

**Comment by jlouns** [comment]
Without more information about the build and how it's configured it's pretty difficult to know why you're getting that error. What does your gulp task look like? For what it's worth, [googling](https://www.google.com/search?q=StringMap+expected+string+key) the error message suggests it's babel related.

**Comment by thany** [comment]
My thoughts exactly. If only there was an option to make errors more verbose. Or if only plugins (like yours 😊) would output where this error occurs...

I've [ducked](https://duckduckgo.com/?q=StringMap+expected+string+key+&t=h_&ia=web) for the error as well, and indeed, something about Babel... Which I'm not using at all. Unless you are, to parse javascript, or something.

**Comment by jlouns** [comment]
The plugin doesn't use babel, so I don't know. You can add `logLevel: 0` to the plugin options for detailed logging.

**Comment by jlouns** [comment]
Closing this. Reopen if it turns out to be a problem with this plugin.
