### ISSUE TITLE
how can i filter non amd js when optimize  

### ISSUE THREAD

**Issue by maodouchen** [jlouns/gulp-requirejs-optimize#24]
![a3377416-5408-4885-abca-0b3b17d1b45a](https://cloud.githubusercontent.com/assets/10754423/18701846/6dccfec0-8011-11e6-9f81-59dce82174f7.png)

i can not  use exclude because there are too many optimize
i want wapper non amd js, but how can i know which js are non amd ??
or filter non amd js ?????

**Comment by jlouns** [comment]
I'm not sure I 100% understand what you're asking, but it sounds like something that could be solved with [requirejs shim config](https://github.com/requirejs/example-jquery-shim) and not something related to this plugin.

**Comment by maodouchen** [comment]
non amd js how optimaze??  
(function () ........)
