### ISSUE TITLE
gulp-util deprecated

### ISSUE THREAD

**Issue by phated** [jlouns/gulp-requirejs-optimize#35]
@jlouns the gulp-util package has been deprecated in favor of using individual modules.  This is due to it containing a hugely out-of-date vinyl that breaks gulp 4.  Please switch to individual modules as outlined in https://github.com/gulpjs/gulp-util/blob/master/README.md

Also, is this project still maintained? Ref https://github.com/gulpjs/gulp/issues/2070

**Comment by Kagami** [comment]
Fixed in #36

**Comment by jlouns** [comment]
Fix integrated in 1.3.0
