### ISSUE TITLE
No errors from r.js optimizer shown?

### ISSUE THREAD

**Issue by spoco2** [jlouns/gulp-requirejs-optimize#4]
Is it just me, or is it known that when using this it silently fails without showing any errors from r.js?

This makes debugging a configuration very difficult.

**Comment by jlouns** [comment]
You're right. I was emitting the errors but they weren't causing the gulp stream to end with an error. Working on a fix now.

**Comment by spoco2** [comment]
Awesome :D I'll grab the latest version now :D

**Comment by jlouns** [comment]
Just published v0.2.0 with this fix. Let me know if you have any issues!
