### ISSUE TITLE
Plugin braking the pipe. Plumber doesn't help

### ISSUE THREAD

**Issue by maciekpaprocki** [jlouns/gulp-requirejs-optimize#5]
Hi I have huge watch task for my project and every single time i save on of js file with some error it's braking. I tried to fix it with plumber, but still brakes. On error is triggered but then it throws error either way. my code:

``` javascript
 return gulp.src(SCRIPTS_SRC + '*.js')
        .pipe(plugins.plumber({
            errorHandler: onError
        }))
        .pipe(plugins.requirejsOptimize())
        .pipe(plugins.plumber.stop())
        .pipe(gulp.dest(SCRIPTS_DEST));
```

Any ideas what might be the issue?

**Comment by jlouns** [comment]
I just put together a quick test where requirejsOptimize throws an error and plumber is keeping the pipe open for me. Are you using the latest versions of the plugins? Is requirejs throwing the error or is it the plugin before it even calls requirejs?

**Comment by maciekpaprocki** [comment]
Ok, I don't know how, but problem stopped existing after update, were it was installed 5 days ago on latest :). Sorry and thanks for support.
