### ISSUE TITLE
Will you add support for "out" option?

### ISSUE THREAD

**Issue by SetTrend** [jlouns/gulp-requirejs-optimize#6]
The RequireJS optimizer may concatenate all input JavaScript files to a single output file. It adds a module name to each of the modules it concatenates in the files. This process cannot be achieved by a Gulp task.

Would you mind adding support for "out" option to gulp-requirejs-optimize?

Background info: I have written a library which I want to offer as a single file. The source code of this library consists of a number of modules, though.

**Comment by jlouns** [comment]
Can you just pass the results to gulp-concat?

**Comment by SetTrend** [comment]
Unfortunately this won't work. When concatenating, the RequireJS Optimizer adds a name to each of the concatenated modules. A common concatenator tool doesn't provide this functionality.

**Comment by jlouns** [comment]
I'm not sure I'm understanding the request. If you have a set of three modules, say, `module-a`, `module-b`, and `module-c` in a `src/modules` folder, and you run that through the following gulp task:

``` js
var gulp = require('gulp');
var concat = require('gulp-concat');
var requirejsOptimize = require('gulp-requirejs-optimize');

gulp.task('scripts', function () {
    return gulp.src('src/modules/*.js')
        .pipe(requirejsOptimize())
        .pipe(concat('combined.js'))
        .pipe(gulp.dest('dist'));
});
```

You'll get something that looks like:

``` js
define("module-a",[],function(){});
define("module-b",[],function(){});
define("module-c",[],function(){});
```

where instead of `[],function(){}`, you'll get the module dependencies and code for the modules, and all of the dependencies will also be in the file. Is this what you're looking for?

**Comment by SetTrend** [comment]
I understand.

Using TypeScript and inheritance, however, this leads to a case of creating double definitions.

Here's the hierarchy of my sample project (abbreviated TypeScript declarations here):

``` javascript
enum TiltDirection;
```

``` javascript
class _TiltHandlerBase;
```

``` javascript
import TiltHandler = require("./_TiltHandlerBase");
import TiltDirection = require("./TiltDirection");
class CssTiltHandler extends TiltHandler;
```

This yields the following defines after `gulp-requirejs-optimize` ran RequireJS Optimizer:

``` javascript
define("TiltDirection.js",["require","exports"],function(e,t) ...
```

``` javascript
define("TiltDirection",["require","exports"],function(e,t) ...
define("_TiltHandlerBase.js",["require","exports","TiltDirection"],function(e,t,n) ...
```

``` javascript
define("TiltDirection",["require","exports"],function(e,t) ...
define("_TiltHandlerBase",["require","exports","TiltDirection"],function(e,t,n) ...
define("jquery",[],function() ...
define("CssTiltHandler.js",["require","exports","./_TiltHandlerBase","./TiltDirection","jquery"],function(e,t,n,r,i) ...
```

So, since the Optimizer has no chance of checking for double entries, double entries are generated (_TiltDirection_ in this case). Which will result in a double definition error, as I presume.

**Comment by jlouns** [comment]
Got it. Yes, that will result in an error. Could you make a new module that requires all of the modules you want exposed and just optimize that?

How would having the `out` parameter able to accept a function value help this?

**Comment by SetTrend** [comment]
Actually, the `out` parameter takes the name of a resulting concatenated file.

So

``` javascript
.pipe(requirejsOptimize({out: 'combined.js'}))
.pipe(gulp.dest('dist'));
```

is equivalent to

``` javascript
.pipe(requirejsOptimize())
.pipe(concat('combined.js'))
.pipe(gulp.dest('dist'));
```

but with the additional benefit of having doubles checked and defines cleaned up.

Actually, I tend to believe it'd be easier and more compliant to have the out option forwarded to the RequireJS optimizer than to having to strive through workarounds.

What's your opinion?

**Comment by jlouns** [comment]
Could you show me an example build, just using `r.js`, that performs the way you're describing?

I tried to do a simple multi-module optimization using the test files in this repo like so:

``` js
var requirejs = require('requirejs');
requirejs.optimize({
    baseUrl: 'test/fixtures',
    modules: [{
        name: 'one'
    }, {
        name: 'two'
    }, {
        name: 'three'
    }],
    out: 'combined.js'
}, function() {
    console.log('Done');
}, function(err) {
    console.error(err);
});
```

And I got this error:

```
Error: If the "modules" option is used, then there should be a "dir" option set and "out" should not be used since "out" is only for single file optimization output.
```

I'm trying to understand the config that you would pass `r.js` to get the output that you want, without defining a new parent module.

**Comment by SetTrend** [comment]
I'm not using _Node_ or _r.js_, I'm afraid. I'm using Microsoft Visual Studio 2015 and, thus, I'm using _gulp_ which is a new addition to Visual Studio's build management tools.

So I must admit that I don't have the slightest idea of how to configure RequireJS Optimizer.

However, since this question seems crucial, I have forwarded your question [here](https://github.com/jrburke/requirejs/issues/1418).

**Comment by jlouns** [comment]
Ok. I'm not sure what you want is possible, but we'll see what they say.

**Comment by jlouns** [comment]
I'm going to close this for now since I think it's a limitation of RequireJS and not this plugin. Feel free to reopen if you get a positive answer from RequireJS.
