### ISSUE TITLE
Build always fails when not wanting to use 'out', but 'dir' instead.

### ISSUE THREAD

**Issue by jvincilione** [jlouns/gulp-requirejs-optimize#7]
Here are the options I'm passing:

```
{
        appDir: dir',
        baseUrl: 'dir/js',
        dir: 'dir/bin',
        paths: {
            'ezpRequireJQuery': 'empty:'
        },
        modules: [
            {
                name: 'main'
            }
        ],
        mainConfigFile: 'dir/js/main.js',
        optimize: 'none'
}
```

I don't have 'out' supplied at all, but I get this error: "The "out" and "dir" options are incompatible. Use "out" if you are targeting a single file for optimization, and "dir" if you want the appDir or baseUrl directories optimized."

I tried setting 'out' to `null` or `false`, but I get the 'out must be a string' error.

**Comment by jlouns** [comment]
Sorry for the delay in answering here. This plugin does not support the `dir` or `modules` options. I'll add a note to the readme about `dir`.

Since you're just optimizing one module (`main`), just remove your `modules` block and pass the `main.js` file as input to the plugin. You can use `gulp.dest` to write it out to the directory you want. For example:

``` js
gulp.src('dir/js/main.js')
    .pipe(requirejsOptimize({
        appDir: 'dir',
        baseUrl: 'dir/js',
        paths: {
            'ezpRequireJQuery': 'empty:'
        },
        mainConfigFile: 'dir/js/main.js',
        optimize: 'none'
    }))
    .pipe(gulp.dest('dir/bin'));
```

**Comment by jvincilione** [comment]
What you're suggesting, I already tried. I found out this plugin is blacklisted by gulp anyway  (all gulp require plugins are), so I'm not using one anymore.

Thanks for the response.

**Comment by jlouns** [comment]
It's not blacklisted... https://github.com/gulpjs/plugins/blob/master/src/blackList.json.
