### ISSUE TITLE
How to exclude dependencies

### ISSUE THREAD

**Issue by adithyan** [jlouns/gulp-requirejs-optimize#8]
While using r.js 

I use this configuration as below to exclude date_picker, how do I do the same using this plugin

> modules: [
>               {
>                   name : 'main',    // no i18n
>                   include : ['main'],   // no i18n
>                   exclude: ['date_picker']  // no i18n
>               }
>               ],

**Comment by vikikamath** [comment]
@adithyan have you tried:

``` javascript
...
 stubModules: ['date_picker'],
...
```

to exclude from optimized build. [Documentation](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L331)

**Comment by adithyan** [comment]
@vikikamath
Thanks for the doc, but it didn't work out

**Comment by jlouns** [comment]
@adithyan You can't use "modules" config with this plugin, but if you're just doing a single module, you don't need it anyway.

Your config would look something like this:

``` js
requirejsOptimize({
  name : 'main', // no i18n
  include : ['main'], // no i18n
  exclude: ['date_picker'] // no i18n
})
```

**Comment by adithyan** [comment]
@jlouns Yes this works fine, I tried this earlier but some how I missed to observer whether it got excluded or not. 

Thanks for pointing out.
