### ISSUE TITLE
Include dependencies in a multi-page webapp

### ISSUE THREAD

**Issue by IceOnFire** [jlouns/gulp-requirejs-optimize#9]
Hi,

I have the exact contrary of [issue 8](https://github.com/jlouns/gulp-requirejs-optimize/issues/8): I cannot seem to include dependencies in my modules.

I'm trying to optimize a multi-page webapp, structured like this:

```
/bower_components
/src/home/home.html
/src/home/home.js
/src/home/homeCtl.js
/src/books/books.html
/src/books/books.js
/src/books/booksCtl.js
/src/common.js
/dist
```

common.js holds RequireJS' configuration, including paths to bower components:

``` javascript
requirejs.config({
  paths: {
    jquery: '/bower_components/jquery/dist/jquery.min',
    ...
  }
}});
```

Since I need one configuration and multiple 'main' files, home.js is shaped like this:

``` javascript
require(['../common']), function() {
  require(['homeCtl']);
});
```

and homeCtl.js is like this:

``` javascript
define(['jquery'], function($) {
  ...
});
```

The problem ism when I try to optimize the home.js module I get a file with just its content, while I was expecting it to traverse all its dependencies to include them.

``` javascript
gulp.src('src/home/home.js', {base: 'src'})
  .pipe(gulpRequirejsOptimize())
  .pipe(gulp.dest('dist'))
```

Result:

``` javascript
require(["../common"],function(){return require(["home/homeCtl"])}),define("homehome.js",function(){});
```

Am I doing something wrong? Thanks in advance!

**Comment by jlouns** [comment]
I think there are two issues here. First, I think because of the way `home.js` is structured, using a nested require form `homeCtl.js` without a reference to the local require instance, it isn't pulling in homeCtl. Is there a reason you can't define `home.js` like this?

``` js
require(['./homeCtl', '../common'], function(homeCtl) {
  // do something here with homeCtl if needed
});
```

Then, I think you need to reference `common.js` as the `mainConfigFile` in your gulp task, like this:

``` js
gulp.src('src/home/home.js', {base: 'src'})
  .pipe(gulpRequirejsOptimize({
    mainConfigFile: 'src/common.js'
  }))
  .pipe(gulp.dest('dist'))
```

Let me know if that fixes things!

**Comment by IceOnFire** [comment]
Wow, thanks for the quick reply!

I'm trying to build a project similar in structure to RequireJS' [multipage app example](https://github.com/requirejs/example-multipage), that's why I have splitted a `homeCtl` which holds the logic and the `home` component which loads the common configuration and then starts the controller. The configuration must be loaded before loading the controller, otherwise its dependencies won't be found correctly.

Adding the `mainConfigFile` solves a part of the problem, now common.js is included in the bundle :) However I still can't find a way to include `home`'s dependencies, not even by getting rid of the intermediate `home` component. I'm starting to think the problem resides somewhere else... Perhaps something going on with the previous steps of the build. I'll let you know in case of progress!

**Comment by IceOnFire** [comment]
After lots of trials and errors I still can't avoid the double require for multi-page apps. As for now the only way I made bundles work is by using r.js directly with the following build.js:

``` javascript
{
  "appDir": "src",
  "baseUrl": ".",
  "mainConfigFile": "src/common.js",
  "dir": "dist",
  "modules": [
    {
      "name": "home/home",
      include: ["homeCtl"]
    },
   ...
}
```

I'm afraid that in this specific case gulp-requirejs-optimize cannot help me, since as far as I understood explicit module inclusion is forbidden... :( What do you think?

**Comment by jlouns** [comment]
Take a look at [this repository](https://github.com/jlouns/requirejs-optimizer-test). Someone had a similar question and that gulpfile was my solution. Might help?

**Comment by IceOnFire** [comment]
Yes, it looks just the same! So apparently I can bypass the limitations in defining modules by using the `function(file) {...}` parameter instead of the usual JSON. Thanks, I'll have a try as soon as I can. ;)
